name: Repo Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

